name: Deploy Flutter Web to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§¾ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ“¦ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"

      - name: ðŸ“¥ Install dependencies
        run: flutter pub get

      - name: ðŸ› ï¸ Build Flutter web
        run: flutter build web --release

      - name: ðŸ”‘ Recreate SSH key from secret
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > odewa-key.pem
          chmod 400 odewa-key.pem

      - name: ðŸ§¹ Clean old files & create temp dir
        run: ssh -o StrictHostKeyChecking=no -i odewa-key.pem ubuntu@${{ secrets.EC2_HOST }} "\mkdir -p /home/ubuntu/web-tmp && sudo rm -rf /var/www/html/*"

      - name: ðŸ“¤ Upload build to EC2 temp folder
        run: scp -o StrictHostKeyChecking=no -i odewa-key.pem -r build/web/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/web-tmp/

      - name: ðŸš€ Move new build & Restart Nginx
        run: ssh -o StrictHostKeyChecking=no -i odewa-key.pem ubuntu@${{ secrets.EC2_HOST }} "\sudo cp -r /home/ubuntu/web-tmp/* /var/www/html/ && sudo systemctl restart nginx"
